
export enum cloudFunctions {
  GET_USER_PROFILE = "getUserProfile",
  CREATE_USER_PROFILE = "createUserProfile",
  CHECK_UNIQUE_USER_FIELDS = "checkUniqueUserFields",
  UPDATE_PRIVACY = "updatePrivacy",
  UPDATE_USER_NAME = "updateUserName",
  UPDATE_USER_PHOTO = "updateUserPhoto",
  UPDATE_USER_PROFILE_NAME = "updateUserProfileName",
  UPDATE_USER_BIO = "updateUserBio",
  UPDATE_USER_EMAIL = "updateUserEmail",
  UPDATE_USER_PHONE = "updateUserPhone",
  GET_GARAGE_DATA = "getGarageData",
  ADD_CAR_TO_GARAGE = "addCarToGarage",
  UPDATE_CAR_IN_GARAGE = "updateCarInGarage",
  DELETE_CAR_IN_GARAGE = "deleteCarInGarage",
  ADD_MODIFICATION_IN_CAR = "addModificationInCar",
  UPDATE_MODIFICATION_IN_CAR = "updateModificationInCar",
  DELETE_MODIFICATION_IN_CAR = "deleteModificationInCar",
}